version:          "001--05-Feb-2024"
copyright:        "2024-2024"
title:            "SP241: Jekyll Template Fork"
author:           "mm0ne"
address:          "Uncharted Region of The Milky Way"
description:
  This is a
  GitHub Page Template description. 
  See also tagline.
disclaimer:
  I have spoken.
tagline:          "This is a GitHub Page Template tagline"
keywords:         "jekyll, testing"
navbarlinks:
- navbar:         "Home"
  link:           "/"
- navbar:         "Links"
  link:           "/LINKS/"
- navbar:         "Tips"
  link:           "/TIPS/"
- navbar:         "Zip File"
  link:           "/template.zip"
- navbar:         "TarBall"
  link:           "/template.tar.bz2"
- navbar:         "GitHub"
  link:           "https://github.com/mm0ne/template/"
- navbar:         "Listing"
  link:           "/000.html"
- navbar:         "About"
  link:           "/ABOUT/"
- navbar:         "GitHub Page"
  link:           "https://mm0ne.github.io/template/"
lang:             "en-US"
sitemap:          "true"
markdown:         "kramdown"
urlweb:           "https://mm0ne.github.io/template/"
urlcontact:       "TBA"
urlgithub:        "https://github.com/mm0ne/template/"
google_analytics: "G-KPSLWHN6H7"
plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-paginate
defaults:
- scope:
    path:    ""
  values:
    layout:  "default"
github:
- metadata

